name: React CI/CD Pipeline for GitHub

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Environment output
        run: echo "Building for '${{ inputs.environment }}' environment"

      - name: Install dependencies
        run: npm ci

      - name: Package app
        run: npm run build

  code-style:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        node-version: ["22.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Environment output
        run: echo "Building for '${{ inputs.environment }}' environment"

      - name: Install dependencies
        run: npm ci

      - name: Code style check
        run: npm run code-style-check
  test-unit:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        node-version: ["22.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Environment output
        run: echo "Building for '${{ inputs.environment }}' environment"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --watch=false

  deploy-to-cloudflare:
    uses: ./.github/workflows/deploy-cloudflare.yml
    secrets: inherit
    needs: [code-style, test-unit]
